version: '3.8'
services:
  clickhouse-keeper:
    image: clickhouse/clickhouse-keeper:25.6
    container_name: clickhouse-keeper
    restart: always
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    volumes:
      - ./config/keeper:/etc/clickhouse-keeper/:ro
    networks:
      - clickhouse-network
    expose:
      - "9181"

  clickhouse-server:
    image: clickhouse/clickhouse-server:25.6
    container_name: clickhouse-server
    restart: always
    cap_add:
      - SYS_NICE
      - NET_ADMIN
      - IPC_LOCK
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    ports:
      - "9000:9000"
      - "8123:8123"
    volumes:
      - ./config/server:/etc/clickhouse-server/:ro
    depends_on:
      - clickhouse-keeper
    networks:
      - clickhouse-network
    environment:
      - CLICKHOUSE_KEEPER_HOST=clickhouse-keeper
      - CLICKHOUSE_KEEPER_PORT=9181
  broker:
    image: apache/kafka:4.2.0-rc1
    container_name: broker
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_LISTENERS: PLAINTEXT://broker:9092,CONTROLLER://broker:9093
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:9092
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@broker:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_NUM_PARTITIONS: 3
    networks:
      - clickhouse-network
    ports:
      - "9092:9092"

networks:
  clickhouse-network:
    driver: bridge
    name: clickhouse-network
